#!/usr/bin/env python3
"""Tables I and III-XII: recompute every number from the saved results and check it against the manuscript.

For each table the numbers are recomputed from the files in results/ (formatting as in the paper)
and compared, in order, with the numbers printed in the corresponding table of paper/main.tex:
  * Table I: prior ranges, compared as numbers with the EOS model definitions;
  * Tables III-VI and IX: every number printed in math mode inside the table body;
  * Tables VII-VIII: the complete table body, character by character (they were generated by this code);
  * Tables X-XII (Appendix C): every number printed in the table body, recomputed from the records in
    results/numerical_checks/ and required to equal the printed value at the printed precision.
Table II lists the likelihood inputs; their sources are given in data/SOURCES.md.
Each rebuilt table is also written to build/tables/. Any difference is reported and fails.
"""
from __future__ import annotations

import argparse
import json
import math
import re
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

import numpy as np

from plotting.common import ROOT

RES = ROOT / "results"
NUMBER = re.compile(r"[-+]?\d+(?:\.\d+)?")


def load(relative: str) -> dict:
    return json.loads((RES / relative).read_text())


# ------------------------------------------------------------------ manuscript access
def table_body(tex: str, label: str) -> str:
    """All tabular environments of the float that carries `label` (concatenated)."""
    start = tex.index(f"\\label{{{label}}}")
    ends = [tex.find(marker, start) for marker in
            ("\\end{resulttablewide}", "\\end{table*}", "\\end{table}", "\\end{resultfigurewide}")]
    end = min(e for e in ends if e >= 0)
    segment = tex[start:end]
    blocks = re.findall(r"\\begin\{tabular\*?\}.*?\\end\{tabular\*?\}", segment, re.S)
    if not blocks:
        raise RuntimeError(f"no tabular found for {label}")
    return "\n".join(blocks)


def math_numbers(body: str) -> list[str]:
    """Numbers printed in math mode; unsigned sub/superscript indices such as R_{1.4} or K_0 are labels."""
    out = []
    for segment in re.findall(r"(?<!\\)\$(.+?)(?<!\\)\$", body, re.S):
        segment = re.sub(r"_\d", "", segment)
        segment = re.sub(r"_\{\d+(?:\.\d+)?\}", "", segment)
        segment = re.sub(r"\^\{\d+(?:\.\d+)?\}", "", segment)
        out += NUMBER.findall(segment)
    return out


def ci(median: float, plus: float, minus: float, decimals: int = 2) -> list[str]:
    return [f"{median:.{decimals}f}", f"+{plus:.{decimals}f}", f"-{minus:.{decimals}f}"]


def ci_dict(value: dict, decimals: int = 2) -> list[str]:
    return ci(value["median"], value["plus"], value["minus"], decimals)


def ci_quantiles(q: list[float], decimals: int = 2) -> list[str]:
    lo, med, hi = q
    return ci(med, hi - med, med - lo, decimals)


# ------------------------------------------------------------------ Table I
def table_I(tex: str) -> tuple[list, list]:
    priors = load("tables/table_I_priors.json")
    body = table_body(tex, "tab:eos-priors")
    printed = [(float(a), float(b)) for a, b in re.findall(r"\[(\d+(?:\.\d+)?),\\,(\d+(?:\.\d+)?)\]", body)]
    low, high = priors["hyperonic"]["low"], priors["hyperonic"]["high"]
    order = [0, 1, 2, 6, 3, 4, 5, 7, 8]  # a_sigma a_omega a_rho rho0 | Gamma_sigma Gamma_omega Gamma_rho | x_sL x_sX
    expected = [(low[i], high[i]) for i in order]
    return expected, printed


# ------------------------------------------------------------------ Table III (A1 summary)
def tidal_statistics(path: Path) -> tuple[dict, dict]:
    saved = np.load(path, allow_pickle=False)
    mass = np.asarray(saved["mass_grid"], dtype=np.float64)
    index = int(np.flatnonzero(np.isclose(mass, 1.4, rtol=0.0, atol=1e-12))[0])
    methods = {"UltraNest": "ultranest_pooled", "TSNPE+MIS": "tsnpe_mis", "A-NET+IS": "anet_is_direct_gmm_320k"}
    reference = np.asarray(saved["band_ultranest_pooled"], dtype=np.float64)
    reference_ess = np.asarray(saved["conditional_ess_ultranest_pooled"])
    summaries, agreement = {}, {}
    for method, key in methods.items():
        band = np.asarray(saved[f"band_{key}"], dtype=np.float64)
        q05, median, q95 = band[:, index]
        summaries[method] = {"median": median, "minus": median - q05, "plus": q95 - median}
        if method == "UltraNest":
            continue
        method_ess = np.asarray(saved[f"conditional_ess_{key}"])
        common = (np.all(np.isfinite(reference), axis=0) & np.all(np.isfinite(band), axis=0)
                  & (reference_ess >= 50.0) & (method_ess >= 50.0))
        agreement[method] = float(np.mean(np.abs(band[[0, 2]][:, common] - reference[[0, 2]][:, common])
                                          / reference[[0, 2]][:, common]) * 100.0)
    return summaries, agreement


def table_III(tex: str) -> tuple[list, list]:
    scalar = load("nucleonic/a1_scalar_summary.json")
    tsnpe = load("nucleonic/tsnpe_mis_a1_summary.json")
    rows = {name: dict(value) for name, value in scalar["rows"].items()}
    for quantity in ("Mmax_msun", "R_at_Mmax_km", "R_1p4_km"):
        rows["TSNPE+MIS"][quantity] = tsnpe["table_scalars"][quantity]
    tidal, tidal_agreement = tidal_statistics(RES / "nucleonic/a1_mass_tidal_bands.npz")
    hyp = load("hyperonic/table_II_IV_hyperonic_values.json")["table_II_hyperonic"]
    expected = []
    for method in ("UltraNest", "TSNPE+MIS", "A-NET+IS"):
        v = rows[method]
        expected += ci_dict(v["Mmax_msun"]) + ci_dict(v["R_at_Mmax_km"]) + ci_dict(v["R_1p4_km"]) + ci_dict(tidal[method], 0)
    for method in ("UltraNest", "TSNPE+MIS", "A-NET+IS"):
        q = hyp["scalars_q05_q50_q95"][method]
        expected += (ci_quantiles(q["Mmax_msun"]) + ci_quantiles(q["R_at_Mmax_km"]) + ci_quantiles(q["R_1p4_km"])
                     + ci_quantiles(q["Lambda_1p4"], 0))
    mr = {"TSNPE+MIS": tsnpe["mass_radius_agreement_with_UltraNest"]["mean_abs_90pct_edge_separation_km"],
          "A-NET+IS": rows["A-NET+IS"]["mean_abs_90pct_edge_separation_from_UltraNest_km"]}
    for method in ("TSNPE+MIS", "A-NET+IS"):
        expected += [f"{mr[method]:.3f}", f"{tidal_agreement[method]:.2f}"]
    for method in ("TSNPE+MIS", "A-NET+IS"):
        expected += [f"{hyp['mean_abs_mass_radius_edge_difference_km'][method]:.3f}",
                     f"{hyp['mean_abs_tidal_edge_difference_percent'][method]:.2f}"]
    return expected, math_numbers(table_body(tex, "tab:a1-summary"))


# ------------------------------------------------------------------ Table IV (nuclear-data changes)
def table_IV(tex: str) -> tuple[list, list]:
    source = load("nucleonic/nuclear_shift_scalar_summary.json")["rows"]
    expected = []
    for configuration, label in (("K0_200", "200"), ("K0_260", "260"), ("Jsym_29", "29"), ("Jsym_36", "36")):
        expected.append(label)
        for method in ("UltraNest", "ANET"):
            row = source[configuration][method]
            expected += ci_dict(row["Mmax_msun"]) + ci_dict(row["R_at_Mmax_km"]) + ci_dict(row["R_1p4_km"])
    return expected, math_numbers(table_body(tex, "tab:nuclear-amortization-summary"))


# ------------------------------------------------------------------ Table V (substituted sources)
def table_V(tex: str) -> tuple[list, list]:
    nuc = load("nucleonic/substituted_source_scalar_summary.json")["rows"]
    j1614 = load("nucleonic/j1614_mass_radius_comparison.json")["scalar_intervals"]
    hyp = load("hyperonic/table_II_IV_hyperonic_values.json")["table_IV_hyperonic"]
    expected = []
    for source in ("J0614", "J1231", "J1614"):
        for method in ("UltraNest", "A-NET+IS"):
            if source == "J1614":
                n = (ci_dict(j1614["maximum_mass_msun"][method]) + ci_dict(j1614["radius_at_maximum_mass_km"][method])
                     + ci_dict(j1614["radius_1p4_km"][method]))
            else:
                row = nuc[source][method]
                n = ci_dict(row["Mmax_msun"]) + ci_dict(row["R_at_Mmax_km"]) + ci_dict(row["R_1p4_km"])
            h = hyp[source][method]
            expected += n + ci_quantiles(h["Mmax_msun"]) + ci_quantiles(h["R_at_Mmax_km"]) + ci_quantiles(h["R_1p4_km"])
    return expected, math_numbers(table_body(tex, "tab:substituted-summary"))


# ------------------------------------------------------------------ Table VI (EN vs UltraNest)
def table_VI(tex: str) -> tuple[list, list]:
    """Green EN values from the 16-row comparison; UltraNest values from the same file, except the four
    hyperonic nuclear-shift rows, which use strictly independent UltraNest seeds only."""
    rows = load("evidence/green_en_vs_ultranest_16_rows.json")["rows"]
    independent = load("evidence/table_VI_independent_ultranest_rows.json")["rows"]
    labels = {"K0_200": ["200"], "K0_260": ["260"], "Jsym_29": ["29"], "Jsym_36": ["36"]}
    expected = []
    for row in rows:
        expected += labels.get(row["configuration"], [])
        un, un_sigma, separation = row["ultranest_log_evidence"], row["ultranest_sigma"], row["separation_sigma"]
        if row["sector"] == "hyperonic" and row["configuration"] in independent:
            u = independent[row["configuration"]]
            assert abs(u["en_logz"] - row["en_log_evidence"]) < 1e-12, "EN values must be unchanged"
            un, un_sigma, separation = u["ultranest_logz"], u["ultranest_sigma"], u["separation_full_precision"]
        expected += [f"{row['en_log_evidence']:.3f}", f"{row['en_sigma']:.3f}",
                     f"{un:.3f}", f"{un_sigma:.3f}", f"{separation:.2f}"]
    return expected, math_numbers(table_body(tex, "tab:en-ultranest"))


# ------------------------------------------------------------------ Table IX (appendix A)
def table_IX(tex: str) -> tuple[list, list]:
    cases = load("appendix/hyperonic_nuclear_amortization_report.json")["cases"]
    expected = []
    for case, label in (("K0_200", "200"), ("K0_260", "260"), ("Jsym_29", "29"), ("Jsym_36", "36")):
        expected.append(label)
        for method in ("ultranest", "anet"):
            s = cases[case]["scalars_q05_q50_q95"][method]
            expected += ci_quantiles(s["Mmax"]) + ci_quantiles(s["R_at_Mmax"]) + ci_quantiles(s["R14"])
    return expected, math_numbers(table_body(tex, "tab:hyp-nuclear-amortization-summary"))


# ------------------------------------------------------------------ Tables VII and VIII (exact text)
V = None
ORDER = ["A1", "K0_200", "K0_260", "Jsym_29", "Jsym_36", "J0614", "J1231", "J1614"]
FIVE = ("A1", "K0_200", "K0_260", "Jsym_29", "Jsym_36")


def sig2(x: float) -> str:
    if x == 0:
        return "0"
    e = math.floor(math.log10(abs(x)))
    v = Decimal(repr(float(x))).quantize(Decimal(1).scaleb(e - 1), rounding=ROUND_HALF_UP)
    e2 = math.floor(math.log10(abs(float(v))))
    return f"{float(v):,.{max(0, 1 - e2)}f}"


def t_s(seconds: float) -> str:
    if seconds < 60:
        return f"{sig2(seconds)} s"
    if seconds < 3600:
        return f"{sig2(seconds / 60)} min"
    return f"{sig2(seconds / 3600)} h"


def t_list(minutes) -> str:
    cells = [t_s(60 * m) for m in minutes]
    units = {c.split()[-1] for c in cells}
    if len(units) == 1:
        return "≈" + "; ".join(c.rsplit(" ", 1)[0] for c in cells) + " " + units.pop()
    return "≈" + "; ".join(cells)


def sci(n: float) -> str:
    if n == 0:
        return "0"
    e = math.floor(math.log10(n))
    mant = sig2(n / 10 ** e)
    if mant == "10":
        mant, e = "1.0", e + 1
    return f"{mant}×10{'⁰¹²³⁴⁵⁶⁷⁸⁹'[e]}"


def rng(values, suffix="×") -> str:
    lo, hi = sig2(min(values)), sig2(max(values))
    return f"≈{lo}{suffix}" if lo == hi else f"≈{lo}–{hi}{suffix}"


def pct(e, n) -> str:
    return f"{100 * e / n:.1f}%"


LABEL = {"A1": "A1 (published data)", "K0_200": "K0 = 200 MeV", "K0_260": "K0 = 260 MeV", "Jsym_29": "Jsym = 29 MeV",
         "Jsym_36": "Jsym = 36 MeV", "J0614": "PSR J0614−3329", "J1231": "PSR J1231−1411", "J1614": "PSR J1614−2230ᵃ"}
TEXLABEL = {"A1": "A1 (published data)", "K0_200": r"$K_0=200$~MeV", "K0_260": r"$K_0=260$~MeV",
            "Jsym_29": r"$J_{\rm sym}=29$~MeV", "Jsym_36": r"$J_{\rm sym}=36$~MeV", "J0614": r"PSR~J0614$-$3329",
            "J1231": r"PSR~J1231$-$1411", "J1614": r"PSR~J1614$-$2230"}
SUP = str.maketrans("⁰¹²³⁴⁵⁶⁷⁸⁹", "0123456789")


def tex_cell(cell: str) -> str:
    s = re.sub(r"×10([⁰¹²³⁴⁵⁶⁷⁸⁹]+)", lambda m: r"$\times10^{" + m.group(1).translate(SUP) + "}$", cell)
    s = s.replace("≈", r"$\approx$").replace("×", r"$\times$").replace("–", "--").replace("%", r"\%")
    return re.sub(r"(\d) (s|min|h)\b", r"\1~\2", s)


def rows_for(method: str, sector: str, constants: dict):
    en = constants["evidence_network"][sector]
    en_times = {"five": en["query_seconds_A1_and_four_nuclear_changes_together"], **en["query_seconds"]}
    tsnpe_factor = (constants["tsnpe_nucleonic_reference_equivalence"]["ultranest_A1_minutes_on_reference_desktop"]
                    / constants["tsnpe_nucleonic_reference_equivalence"]["ultranest_A1_minutes_on_tsnpe_desktop"])
    R, U = V["rows"][sector], V["ultranest"][sector]
    main, summary, times, evals = [], [], {}, {}
    for c in ORDER:
        u = U[c]
        if method == "A-NET+IS":
            a = R[f"A-NET+IS {c}"]
            sec, ev = a["seconds"], a["evaluations"]
            mcells = [f"≈{t_s(sec)}", f"{ev:,}", f"≈{sig2(a['ess'])} ({pct(a['ess'], ev)})"]
        else:
            sec = en_times["five"] if c in FIVE else en_times[c]
            ev = 0
            mcells = [f"≈{t_s(sec)}{' (all five)' if c in FIVE else ''}", "0", "–"]
        times[c], evals[c] = sec, ev
        ess = "; ".join(sig2(s) for s in u["ess"])
        eff = "; ".join(pct(s, e) for s, e in zip(u["ess"], u["evaluations"]))
        ucells = [t_list(u["equivalent_minutes"]), "≈" + "; ".join(sci(e) for e in u["evaluations"]), f"≈{ess} ({eff})"]
        main.append([c] + mcells + ucells + [rng([60 * m / sec for m in u["equivalent_minutes"]])])
    if method == "A-NET+IS":
        s = R["A-NET one-time setup"]
        one_sec, one_ev = s["seconds"], s["evaluations"]
        per = sum(times.values())
    else:
        one_sec, one_ev = en["one_time_seconds"], en["one_time_exact_likelihood_evaluations"]
        per = en_times["five"] + en_times["J0614"] + en_times["J1231"] + en_times["J1614"]
    tot_sec, tot_ev = one_sec + per, one_ev + sum(evals.values())
    u_lo = sum(min(U[c]["equivalent_minutes"]) for c in ORDER)
    u_hi = sum(max(U[c]["equivalent_minutes"]) for c in ORDER)
    e_lo = sum(min(U[c]["evaluations"]) for c in ORDER)
    e_hi = sum(max(U[c]["evaluations"]) for c in ORDER)
    u_tot = f"≈{t_s(60 * u_lo)}" if t_s(60 * u_lo) == t_s(60 * u_hi) else f"≈{sig2(u_lo / 60)}–{sig2(u_hi / 60)} h"
    e_tot = f"≈{sci(e_lo)}" if sci(e_lo) == sci(e_hi) else f"≈{sci(e_lo).split('×')[0]}–{sci(e_hi)}"
    summary.append([f"{method} one-time cost before the first query", f"≈{t_s(one_sec)}",
                    "0" if one_ev == 0 else "≈" + sci(one_ev), "–"])
    if method == "A-NET+IS":
        t = R["TSNPE+MIS A1"]
        t_min = t["minutes"] * (tsnpe_factor if sector == "nucleonic" else 1.0)
        lab = "reference-equivalent estimate" if sector == "nucleonic" else "recorded-stage parallel-equivalent"
        summary.append([f"TSNPE+MIS, A1 only (ESS ≈{sig2(t['ess'])}, {pct(t['ess'], t['evaluations'])})",
                        f"≈{t_s(60 * t_min)} ({lab})", f"≈{sci(t['evaluations'])}",
                        f"{rng([m / t_min for m in U['A1']['equivalent_minutes']])} faster"])
    summary.append(["All eight configurations, including the one-time cost; one UltraNest run per configuration "
                    "(range over independent seeds)", f"≈{t_s(tot_sec)} vs {u_tot}", f"≈{sci(tot_ev)} vs {e_tot}",
                    f"{rng([60 * u_lo / tot_sec, 60 * u_hi / tot_sec])} faster"])
    return main, summary


PT = {"A-NET+IS": [71, 33, 40, 55, 39.2, 68.3, 96.3, 42], "EN": [71, 63, 40, 40, 39.2, 68.3, 96.3, 69.2]}
WIDTHS = {k: [w / 510 for w in v] for k, v in PT.items()}
SUMW = [w / 510 for w in (236, 100, 97.5, 60)]
RR, END = "\\raggedright ", r" \tabularnewline"


def row(cells) -> str:
    return "    " + " & ".join(RR + c for c in cells) + END


def colspec(ws):
    return "@{\\extracolsep{\\fill}}" + "".join(f"p{{{w:.4f}\\textwidth}}" for w in ws) + "@{}"


def cost_tabulars(method: str, constants: dict) -> tuple[str, list[list[str]]]:
    m = method
    L = [f"  \\begin{{tabular*}}{{\\textwidth}}{{{colspec(WIDTHS[m])}}}", r"    \toprule",
         f"    & \\multicolumn{{3}}{{c}}{{{m}}} & \\multicolumn{{3}}{{c}}{{UltraNest}} &" + END,
         r"    \cmidrule(lr){2-4}\cmidrule(lr){5-7}",
         row(["Configuration", "Time", r"Likelihood\\evaluations", r"ESS\\(efficiency)", "Time",
              r"Likelihood\\evaluations", r"ESS\\(efficiency)", f"{m}\\\\faster by"]), r"    \midrule"]
    markdown, summaries = [], {}
    for i, (sector, title) in enumerate((("nucleonic", r"Nucleonic DDB"), ("hyperonic", r"Hyperonic DDB$\Lambda\Xi^-$"))):
        main, summ = rows_for(method, sector, constants)
        summaries[sector] = summ
        if i:
            L.append(r"    \addlinespace[2pt]")
        L.append(f"    \\multicolumn{{8}}{{@{{}}l}}{{\\textit{{{title}}}}}" + END)
        for r in main:
            L.append(row([TEXLABEL[r[0]]] + [tex_cell(x) for x in r[1:]]))
            markdown.append([sector, LABEL[r[0]]] + r[1:])
    L += [r"    \bottomrule", r"  \end{tabular*}", r"  \par\vspace{3pt}", f"  \\begin{{tabular*}}{{\\textwidth}}{{{colspec(SUMW)}}}",
          r"    \toprule", row(["Summary", "Time", "Likelihood evaluations", "Compared with UltraNest"]), r"    \midrule"]
    for i, (sector, title) in enumerate((("nucleonic", r"Nucleonic DDB"), ("hyperonic", r"Hyperonic DDB$\Lambda\Xi^-$"))):
        if i:
            L.append(r"    \addlinespace[2pt]")
        L.append(f"    \\multicolumn{{4}}{{@{{}}l}}{{\\textit{{{title}}}}}" + END)
        for r in summaries[sector]:
            L.append(row([tex_cell(x) for x in r]))
            markdown.append([sector] + r)
    L += [r"    \bottomrule", r"  \end{tabular*}"]
    return "\n".join(L), markdown


def table_cost(tex: str, label: str, method: str) -> tuple[list, list, list]:
    global V
    V = load("cost/table_VII_VIII_values.json")
    constants = load("cost/en_and_tsnpe_timing_constants.json")
    rebuilt, markdown = cost_tabulars(method, constants)
    expected = re.findall(r"\\begin\{tabular\*\}.*?\\end\{tabular\*\}", rebuilt, re.S)
    printed = re.findall(r"\\begin\{tabular\*\}.*?\\end\{tabular\*\}", table_body(tex, label), re.S)
    squash = lambda s: " ".join(s.split())  # noqa: E731
    return [squash(x) for x in expected], [squash(x) for x in printed], markdown


# ------------------------------------------------------------------ Tables X-XII (Appendix C)
RC = RES / "numerical_checks"


class Raw(float):
    """A record value: the printed number must equal it rounded to the printed number of decimals."""


def largest_changes(changes: list[dict]) -> list[Raw]:
    """Largest |change| over configurations: R1.4 percentiles, band edges, median Lambda1.4, log Z."""
    rows = [(max(abs(x) for x in c["shift"]["R14"]), c["band_max_abs_shift_km"], abs(c["shift"]["L14"][1]), abs(c["dlogZ"]))
            for c in changes]
    return [Raw(max(r[i] for r in rows)) for i in range(4)]


def table_X(tex: str) -> tuple[list, list]:
    conv = [json.loads(f.read_text()) for f in sorted((RC / "appendix_c").glob("conv_*.json"))]
    prior = [json.loads(f.read_text()) for f in sorted((RC / "appendix_c").glob("prior_*.json"))]
    extra = json.loads((RC / "appendix_c/extra_likelihood_checks/extra_likelihood_checks.json").read_text())["per_configuration"]
    quadrature = [v[k] for r in conv for v in r["nicer"].values()
                  for k in ("mass_points_400", "mass_points_2000", "grid_400", "refined_grid400_points2000")]
    quadrature += [r["gw"]["q_points_200"] for r in conv] + [r["all_numerical_refinements_combined"] for r in conv]
    kde_nicer = [v[k] for r in conv for v in r["nicer"].values() for k in v if k.startswith("kde_subsample")]
    kde_gw = [r["gw"][k] for r in conv for k in r["gw"] if k.startswith("kde_subsample") or k == "kde_all_8078_samples"]

    def pick(*names: str) -> list[dict]:
        return [c[n] for c in extra.values() for n in names if n in c]

    rows = [([], quadrature), ([], kde_nicer), ([], kde_gw), (["25"], pick("nicer_bw_0.06", "nicer_bw_0.10")),
            (["0.8", "1.25"], pick("gw_bw_x0.8", "gw_bw_x1.25")), ([], pick("gw_chirp_mass_marginalized")),
            (["80"], pick("dense_sequence")), ([], [r["gw"]["sensitivity_divide_component_mass_prior"] for r in conv]),
            ([], [r["both"] for r in prior])]
    expected = []
    for labels, changes in rows:
        expected += labels + largest_changes(changes)
    return expected, math_numbers(table_body(tex, "tab:numerics"))


def table_XI(tex: str) -> tuple[list, list]:
    steps = json.loads((RC / "appendix_c/step_posteriors.json").read_text())
    expected = ["5", "50", "95"]  # column headers R_{1.4}^{5%}, ^{50%}, ^{95%}
    for key in ("A1_steps64_n8000_s0", "A1_steps256_n8000_s0", "A1_steps1024_n4000_s0"):
        r = steps[key]
        sd = r["bootstrap_sd"]  # R1.4 5/50/95, Mmax 50, Lambda1.4 50, band edges
        expected += [Raw(r["ess"]), Raw(r["log_evidence"]), Raw(r["R14"][0]), Raw(r["R14"][1]), Raw(1000 * sd[1]),
                     Raw(r["R14"][2]), Raw(r["L14"][1]), Raw(sd[4])]
    return expected, math_numbers(table_body(tex, "tab:heun"))


def importance_log_evidence(logl, logq, logp) -> tuple[float, float]:
    lw = np.where(np.isfinite(logp + logl - logq), logp + logl - logq, -np.inf)
    m = lw.max()
    w = np.exp(lw - m)
    return float(m + np.log(w.mean())), float(np.std(w) / (np.sqrt(len(lw)) * w.mean()))


def table_XII(tex: str) -> tuple[list, list]:
    en = {(r["sector"], r["configuration"]): r for r in load("evidence/green_en_vs_ultranest_16_rows.json")["rows"]}
    estimate = {}
    for cfg in ("A1", "J0614", "J1231", "J1614"):
        c = np.load(RES / f"hyperonic/{cfg}/anet_certificate.npz")
        estimate[("hyperonic", cfg)] = (float(c["log_evidence"]), float(c["log_evidence_standard_error"]))
    shifts = np.load(ROOT / "route2/fixtures/hyperonic_anet/nuclear_shift_certificates.npz")
    for cfg in ("K0_200", "K0_260", "Jsym_29", "Jsym_36"):
        logp = -float(np.sum(np.log(shifts[f"{cfg}__prior_high"] - shifts[f"{cfg}__prior_low"])))
        estimate[("hyperonic", cfg)] = importance_log_evidence(shifts[f"{cfg}__logl"], shifts[f"{cfg}__logq"], logp)
    files = {"A1": "A1_steps1024_n4000_s0", "K0_200": "ev1024_K0_200_A1", "K0_260": "ev1024_K0_260_A1",
             "Jsym_29": "ev1024_Jsym_29_A1", "Jsym_36": "ev1024_Jsym_36_A1", "J0614": "ev1024_A1_J0614",
             "J1231": "ev1024_A1_J1231", "J1614": "ev1024_A1_J1614"}
    for cfg, name in files.items():
        d = np.load(RC / f"appendix_c/{name}.npz")
        estimate[("nucleonic", cfg)] = (float(d["log_evidence"]), float(d["log_evidence_se"]))
    labels = {"K0_200": ["200"], "K0_260": ["260"], "Jsym_29": ["29"], "Jsym_36": ["36"]}
    expected = []
    for cfg in ORDER:
        expected += labels.get(cfg, [])
        for sector in ("nucleonic", "hyperonic"):
            value, error = estimate[(sector, cfg)]
            row = en[(sector, cfg)]
            en_value, en_sigma = round(row["en_log_evidence"], 3), round(row["en_sigma"], 3)  # as printed in Table VI
            expected += [Raw(value), Raw(error), Raw((en_value - value) / en_sigma)]
    return expected, math_numbers(table_body(tex, "tab:en-is"))


def compare_rounded(name: str, expected: list, printed: list) -> dict:
    if len(expected) != len(printed):
        return {"table": name, "status": "FAIL", "counts": [len(expected), len(printed)]}
    for position, (e, p) in enumerate(zip(expected, printed)):
        if isinstance(e, Raw):
            decimals = len(p.split(".")[1]) if "." in p else 0
            same = abs(float(p) - e) <= 0.5 * 10.0 ** -decimals + 1e-9
        else:
            same = e == p
        if not same:
            return {"table": name, "status": "FAIL", "first_difference_at": position, "recomputed": repr(e), "manuscript": p}
    return {"table": name, "status": "PASS", "items_compared": len(expected)}


# ------------------------------------------------------------------ driver
def compare(name: str, expected: list, printed: list) -> dict:
    if expected == printed:
        return {"table": name, "status": "PASS", "items_compared": len(expected)}
    for position, (a, b) in enumerate(zip(expected, printed)):
        if a != b:
            return {"table": name, "status": "FAIL", "first_difference_at": position,
                    "recomputed": str(a)[:300], "manuscript": str(b)[:300],
                    "counts": [len(expected), len(printed)]}
    return {"table": name, "status": "FAIL", "counts": [len(expected), len(printed)]}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manuscript", type=Path, default=ROOT / "paper/main.tex")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "build/tables")
    arguments = parser.parse_args()
    arguments.output_dir.mkdir(parents=True, exist_ok=True)
    tex = arguments.manuscript.read_text()
    results = []
    for name, builder in (("Table I", table_I), ("Table III", table_III), ("Table IV", table_IV),
                          ("Table V", table_V), ("Table VI", table_VI), ("Table IX", table_IX)):
        expected, printed = builder(tex)
        results.append(compare(name, expected, printed))
        (arguments.output_dir / f"{name.replace(' ', '_')}_numbers.json").write_text(
            json.dumps({"recomputed_in_table_order": expected}, indent=0, default=list) + "\n")
    for name, label, method in (("Table VII", "tab:cost", "A-NET+IS"), ("Table VIII", "tab:en-cost", "EN")):
        expected, printed, markdown = table_cost(tex, label, method)
        results.append(compare(name, expected, printed))
        lines = ["| " + " | ".join(r) + " |" for r in markdown]
        (arguments.output_dir / f"{name.replace(' ', '_')}.md").write_text("\n".join(lines) + "\n")
    for name, builder in (("Table X", table_X), ("Table XI", table_XI), ("Table XII", table_XII)):
        expected, printed = builder(tex)
        results.append(compare_rounded(name, expected, printed))
        (arguments.output_dir / f"{name.replace(' ', '_')}_numbers.json").write_text(
            json.dumps({"recomputed_in_table_order": [float(x) if isinstance(x, Raw) else x for x in expected]}, indent=0) + "\n")
    order = ["Table I", "Table III", "Table IV", "Table V", "Table VI", "Table VII", "Table VIII", "Table IX",
             "Table X", "Table XI", "Table XII"]
    results.sort(key=lambda r: order.index(r["table"]))
    (arguments.output_dir / "tables_check.json").write_text(json.dumps(results, indent=1) + "\n")
    for r in results:
        detail = f"{r.get('items_compared', '')} numbers/blocks identical" if r["status"] == "PASS" else json.dumps(r)
        print(f"[tables] {r['status']} {r['table']}: {detail}")
    return 0 if all(r["status"] == "PASS" for r in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
